### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by TheStaticVoid** [TheStaticVoid/Solar-Panels#1]
- [x] Add Cloth Config
- [x] Add more tiers of solar
- [x] Textures for each tier
- [x] Recipes
- [x] Custom item for recipes(?)
- [x] Remove TR and RC import
- [ ] Bug testing
- [x] Add README
